### ISSUE TITLE
Load data from Ajax

### ISSUE THREAD

**Issue by franlopezraris** [freakazoid41/pickle_tree#1]
Hi,

is it possible to load the data from ajax?
I am trying this but it doesn't work for me.

        function GetNodos() {
            $.ajax({
                type: 'GET',
                url: '/Carta/GetFamiliasV2/' + '@Model.idcarta',
                dataType: 'json',
                contextType: "application/json",
                traditional: true
            }).done(function (datos) {
                var nodos = JSON.stringify(datos);
                for (var i = 0; i < nodos.length; i += 1) {
                    let new_node = arbol_familias.createNode(nodos[i]);
                }
            }).fail(function () {
                swal("Error!", "Error al consultar las familias", "warning");
            });
        }

**Comment by freakazoid41** [comment]
Of course is possible you can reach the examples from https://github.com/freakazoid41/pickle_tree. Also you can look live example from http://tree.picklecan.me/
if there is a problem you can send console logs or detailed error text any time then i will explain what is wrong about situation.I suggest you should check your node object keys first.
________________________________
Gönderen: franlopezraris ***@***.***>
Gönderildi: 13 Nisan 2021 Salı 14:08
Kime: freakazoid41/pickle_tree ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: [freakazoid41/pickle_tree] Load data from Ajax (#1)


Hi,

is it possible to load the data from ajax?
I am trying this but it doesn't work for me.

    function GetNodos() {
        $.ajax({
            type: 'GET',
            url: '/Carta/GetFamiliasV2/' + '@Model.idcarta',
            dataType: 'json',
            contextType: "application/json",
            traditional: true
        }).done(function (datos) {
            var nodos = JSON.stringify(datos);
            for (var i = 0; i < nodos.length; i += 1) {
                let new_node = arbol_familias.createNode(nodos[i]);
            }
        }).fail(function () {
            swal("Error!", "Error al consultar las familias", "warning");
        });
    }
