### ISSUE TITLE
Possible to search by path?

### ISSUE THREAD

**Issue by Mashiane** [freakazoid41/pickle_tree#4]
Hi

Is it possible to find a node using a path?

**Comment by freakazoid41** [comment]
hi 

Right now you can search from node title already and if you want to find special node from its id its possible too

Relative examples are bellow :

//for getting node from it's id :
let our_node = tree.getNode('5');

//for deleting node
our_node.deleteNode();

//for toggling
our_node.toggleNode();
    
//for toggle on all parents and find location of node
our_node.showFamily();

//for getting it's childs
our_node.getChilds();

//for check / uncheck node
our_node.toggleCheck(true / false);
